name: traffic
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  url_launcher: ^6.2.4
  photo_view: ^0.14.0
  shared_preferences: ^2.5.3
  firebase_core: ^3.13.0
  cloud_firestore: ^5.6.6
  firebase_storage: ^12.4.5
  connectivity_plus: ^5.0.1
  flame_audio: ^2.11.4
  image_picker: ^1.1.2
  firebase_auth: ^5.5.2
  local_auth: ^2.3.0
  path: ^1.8.0
  provider: ^6.1.5
  percent_indicator: ^4.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/police.png"

flutter_lints: ^2.0.0
flutter_zoom_driver: ^2.1.1

flutter:
  uses-material-design: true
  assets:
    - assets/

